version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
#    image: pihole/pihole:v5.1.2
    image: pihole/pihole:latest
    environment:
      # set a secure password here or the default will be firewalla
      WEBPASSWORD: 'firewalla'
    # Volumes store your data between container upgrades
    volumes:
      - '/data/pi-hole/etc-pihole/:/etc/pihole/'
      - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
      - '/etc/localtime:/etc/localtime:ro'
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    networks:
      default:
        # static IP address for pi-hole
        ipv4_address: 172.16.0.2
networks:
  default:
    driver: bridge
    ipam:
     config:
       # your chosen docker network here
       - subnet: 172.16.0.0/24
